-- +goose Up
CREATE TABLE reviews (
  id INTEGER NOT NULL AUTO_INCREMENT,
  lecture_id VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  utime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- +goose Down
DROP TABLE reviews;
